[package]
name = "example"
edition = "2024.beta"
version = "0.0.1"

[dependencies.Switchboard]
git = "https://github.com/switchboard-xyz/sui.git"
subdir = "on_demand"
rev = "main"

[addresses]
example = "0x0"
std = "0x1"
sui =  "0x2"
switchoard = "0x846e4d912db89d9db299db0cc7f56f281846ce058fb336ba76e39927836da0ac"